# TODO 1: Define tile size, grid dimensions, and screen dimensions
TILESIZE = 0
GRID_WIDTH = 0
GRID_HEIGHT = 0
SCREEN_WIDTH = 0
SCREEN_HEIGHT = 0

class GameState:
    # TODO 2: Define GameState states (START_SCREEN, CHARACTER_SELECT, GAMEPLAY, GAME_OVER)
    pass

# --- DIFFICULTY CONSTANTS ---
DIFFICULTY_MEDIUM_ENEMIES = 2
DIFFICULTY_MEDIUM_SCORE = 2.0
DIFFICULTY_MEDIUM_SPEED = 1.5
DIFFICULTY_MEDIUM_DELAY = 1

class SearchAlgorithm:
    BFS_SEARCH = 1
    DIJKSTRA_SEARCH = 2

ENEMY_1_ALGORITHM = SearchAlgorithm.DIJKSTRA_SEARCH
ENEMY_2_ALGORITHM = SearchAlgorithm.BFS_SEARCH

# --- SKILL CONSTANTS ---
SKILL_COST = 1000
PROJECTILE_SPEED = 5
PROJECTILE_SIZE = 8
RESPAWN_DELAY_EASY = 5 
RESPAWN_DELAY_NORMAL = 10
RESPAWN_DELAY_HARD = 15

POWERUP_DROP_CHANCE = 0.1
POWERUP_FREEZE_DURATION = 300